import PDFDocument from "pdfkit";
import type { Response } from "express";

const RUST = "#EB4A26";
const INK = "#1b1510";
const MUTED = "#8b8275";
const LINE = "#eceae4";

function fmtDate(d?: Date | string | null): string {
  if (!d) return "—";
  return new Date(d).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
}

/**
 * Streams a clean, branded invoice PDF straight to the HTTP response.
 * We prefix amounts with the currency CODE (e.g. "NGN") rather than the ₦ glyph,
 * since the built-in PDF fonts don't include the naira symbol.
 */
export function streamInvoicePdf(res: Response, { invoice, shop }: { invoice: any; shop: any }) {
  const currency = shop?.currency || "NGN";
  const money = (n: number) => `${currency} ${Math.round(n).toLocaleString()}`;

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${invoice.number}.pdf"`);
  doc.pipe(res);

  const left = 50;
  const right = 545;

  // top accent band
  doc.rect(0, 0, 595, 8).fill(RUST);

  // shop name + INVOICE
  doc.fillColor(INK).font("Helvetica-Bold").fontSize(22).text(shop?.name || "Your Shop", left, 48);
  if (shop?.type) doc.font("Helvetica").fontSize(10).fillColor(MUTED).text(shop.type, left, 76);
  doc.fillColor(INK).font("Helvetica-Bold").fontSize(26).text("INVOICE", left, 48, { width: right - left, align: "right" });
  doc.font("Helvetica").fontSize(10).fillColor(MUTED).text(`#${invoice.number}`, left, 80, { width: right - left, align: "right" });

  // status badge
  const paid = invoice.status === "paid";
  const badge = paid ? "PAID" : "UNPAID";
  doc.font("Helvetica-Bold").fontSize(9);
  const bw = doc.widthOfString(badge) + 18;
  const bx = right - bw;
  doc.roundedRect(bx, 98, bw, 18, 4).fill(paid ? "#12805c" : RUST);
  doc.fillColor("#ffffff").text(badge, bx, 103, { width: bw, align: "center" });

  // bill to + dates
  const y0 = 145;
  doc.fillColor(MUTED).font("Helvetica-Bold").fontSize(9).text("BILL TO", left, y0);
  doc.fillColor(INK).font("Helvetica").fontSize(13).text(invoice.customerName, left, y0 + 14);

  doc.fillColor(MUTED).font("Helvetica-Bold").fontSize(9).text("ISSUED", 360, y0);
  doc.fillColor(INK).font("Helvetica").fontSize(11).text(fmtDate(invoice.createdAt), 360, y0 + 13);
  doc.fillColor(MUTED).font("Helvetica-Bold").fontSize(9).text("DUE", 460, y0);
  doc.fillColor(INK).font("Helvetica").fontSize(11).text(fmtDate(invoice.dueDate), 460, y0 + 13);

  // table header
  let y = 205;
  doc.rect(left, y, right - left, 24).fill("#f3f1ec");
  doc.fillColor(MUTED).font("Helvetica-Bold").fontSize(9);
  doc.text("ITEM", left + 10, y + 8);
  doc.text("QTY", 315, y + 8, { width: 45, align: "right" });
  doc.text("UNIT PRICE", 365, y + 8, { width: 95, align: "right" });
  doc.text("AMOUNT", 465, y + 8, { width: right - 465 - 10, align: "right" });
  y += 34;

  // rows
  doc.font("Helvetica").fontSize(11);
  for (const it of invoice.items as Array<{ name: string; quantity: number; unitPrice: number }>) {
    const amount = it.quantity * it.unitPrice;
    doc.fillColor(INK).text(it.name, left + 10, y, { width: 250 });
    doc.fillColor(INK).text(String(it.quantity), 315, y, { width: 45, align: "right" });
    doc.text(money(it.unitPrice), 365, y, { width: 95, align: "right" });
    doc.text(money(amount), 465, y, { width: right - 465 - 10, align: "right" });
    y += 24;
    doc.moveTo(left, y - 6).lineTo(right, y - 6).strokeColor(LINE).lineWidth(1).stroke();
  }

  // total
  y += 12;
  doc.font("Helvetica-Bold").fontSize(13).fillColor(INK).text("Total", 360, y, { width: 95, align: "right" });
  doc.fillColor(RUST).text(money(invoice.total), 465, y, { width: right - 465 - 10, align: "right" });

  // notes
  if (invoice.notes) {
    y += 48;
    doc.font("Helvetica-Bold").fontSize(9).fillColor(MUTED).text("NOTES", left, y);
    doc.font("Helvetica").fontSize(10).fillColor(INK).text(invoice.notes, left, y + 13, { width: right - left });
  }

  // footer
  doc.font("Helvetica").fontSize(9).fillColor(MUTED)
    .text("Generated by Kredex — your business runs itself.", left, 790, { width: right - left, align: "center" });

  doc.end();
}
