import { Icon } from '@iconify/react'
import type { Invoice } from '../../lib/api'
import { useAuth } from '../../auth/AuthContext'
import { useMoney } from '../../lib/useMoney'

const fmtDate = (iso: string) => new Date(iso).toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' })

export default function InvoicePreview({
  invoice,
  onClose,
  onDownload,
  downloading,
}: {
  invoice: Invoice
  onClose: () => void
  onDownload: () => void
  downloading: boolean
}) {
  const { shop } = useAuth()
  const { money } = useMoney()
  const paid = invoice.status === 'paid'
  const initials = (shop?.name || 'K').split(/\s+/).filter(Boolean).slice(0, 2).map((w) => w[0]?.toUpperCase()).join('') || 'K'

  return (
    <div className="fixed inset-0 z-[80] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-zinc-950/50 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-md">
        {/* the invoice itself — always light, like a printed document */}
        <div className="no-scrollbar max-h-[78vh] overflow-y-auto rounded-2xl bg-white p-6 text-zinc-900 shadow-2xl">
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-center gap-2.5">
              <span className="grid size-9 place-items-center rounded-lg bg-[#EB4A26] text-sm font-bold text-white">{initials}</span>
              <div>
                <p className="font-semibold leading-none">{shop?.name}</p>
                <p className="mt-1 font-mono text-[10px] uppercase tracking-widest text-zinc-400">{shop?.type || 'Shop'}</p>
              </div>
            </div>
            <div className="text-right">
              <p className="font-mono text-lg font-bold">{invoice.number}</p>
              <p className="text-xs text-zinc-400">{fmtDate(invoice.createdAt)}</p>
              <span className={`mt-1 inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold ${paid ? 'bg-emerald-50 text-emerald-600' : 'bg-[#EB4A26]/10 text-[#EB4A26]'}`}>
                <Icon icon={paid ? 'solar:check-circle-bold' : 'solar:clock-circle-linear'} width="11" />
                {paid ? 'PAID' : 'UNPAID'}
              </span>
            </div>
          </div>

          <div className="mt-6 grid grid-cols-2 gap-4 border-t border-zinc-100 pt-4">
            <div>
              <p className="font-mono text-[10px] uppercase tracking-widest text-zinc-400">From</p>
              <p className="mt-1 text-sm font-medium">{shop?.name}</p>
            </div>
            <div>
              <p className="font-mono text-[10px] uppercase tracking-widest text-zinc-400">Bill to</p>
              <p className="mt-1 text-sm font-medium">{invoice.customerName}</p>
            </div>
          </div>

          <div className="mt-5 overflow-hidden rounded-xl border border-zinc-100">
            <div className="flex items-center gap-2 bg-zinc-50 px-3 py-2 font-mono text-[10px] uppercase tracking-wider text-zinc-400">
              <span className="flex-1">Item</span>
              <span className="w-9 text-center">Qty</span>
              <span className="w-24 text-right">Unit</span>
              <span className="w-24 text-right">Total</span>
            </div>
            {invoice.items.map((it, i) => (
              <div key={i} className="flex items-center gap-2 border-t border-zinc-50 px-3 py-2.5 text-sm">
                <span className="flex-1">{it.name}</span>
                <span className="w-9 text-center text-zinc-500">{it.quantity}</span>
                <span className="w-24 text-right text-zinc-500">{money(it.unitPrice)}</span>
                <span className="w-24 text-right font-medium">{money(it.quantity * it.unitPrice)}</span>
              </div>
            ))}
            <div className="flex items-center justify-between bg-[#EB4A26]/5 px-3 py-3">
              <span className="text-sm font-semibold text-zinc-700">Grand Total</span>
              <span className="font-mono text-lg font-bold text-[#EB4A26]">{money(invoice.total)}</span>
            </div>
          </div>

          {invoice.notes && (
            <p className="mt-4 text-xs text-zinc-500">
              <span className="font-medium text-zinc-700">Note: </span>
              {invoice.notes}
            </p>
          )}

          <p className="mt-5 border-t border-zinc-100 pt-3 text-center font-mono text-[10px] text-zinc-300">
            Generated by Kredex · {invoice.number}
          </p>
        </div>

        <button
          onClick={onDownload}
          disabled={downloading}
          className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#EB4A26] py-3.5 font-semibold text-white shadow-lg shadow-[#EB4A26]/30 transition-transform hover:-translate-y-0.5 disabled:opacity-60"
        >
          <Icon icon={downloading ? 'solar:refresh-linear' : 'solar:download-minimalistic-linear'} width="18" className={downloading ? 'animate-spin' : ''} />
          {downloading ? 'Preparing…' : 'Download PDF'}
        </button>
        <button onClick={onClose} className="mt-2 w-full text-center text-xs text-white/70 hover:text-white">
          Close
        </button>
      </div>
    </div>
  )
}
